### ISSUE TITLE
5.1.0 version pod cannot be used as a library

### ISSUE THREAD

**Issue by dvor** [robbiehanson/KissXML#70] opened 2016-07-07 08:10 UTC
5.1.0 version has some swift files includes, which requires us to have `use_frameworks!` flags for all pods. This is incompatible with Objective C project that uses libraries.

**Comment by chrisballinger** [comment] 2016-07-07 17:37
Ah yes good point. Since the Swift code isn't strictly necessary unless you want to use the NSXML API in Swift, perhaps it would be better suited to a subspec. I'll release 5.1.1 with a fix asap.

We should probably add a test target for iOS 7 so regressions can be caught in the future.

**Comment by chrisballinger** [comment] 2016-07-07 20:24
Should be fixed in 5.1.1

**Closed by chrisballinger** 2016-07-07 20:24 UTC

**Comment by dvor** [comment] 2016-07-08 07:32
Now it works, thanks!
